---
# The role for redis
#
# Usage: { role: redis, install_path: /usr/local, port: 27017, db_path: /opt, redis_file: redis_2.8 }
#

- name: check redis
  command: "/usr/local/bin/redis-server -v"
  register: redis_result
  ignore_errors: true
  when: state != "absent"
  tags: redis

- name: rsync {{ redis_file }}
  synchronize: src={{ package_path }}/redis/{{ redis_file }} dest=/tmp
  when: redis_result is defined and redis_result.rc !=0 or state == "upgrade"
  tags: redis

- name: make redis
  command: chdir=/tmp/{{ redis_file }} make install -j8
  when: state == "upgrade" or redis_result is defined and redis_result.rc != 0
  tags: redis

- name: deploy redis_{{ port }} init script
  template: src=redis dest=/etc/init.d/redis_{{ port }} mode=0755
  when: state != "absent"
  tags: redis

- name: create /etc/redis/{{ port }}
  file: path=/etc/redis/{{ port }} state=directory recurse=yes
  when: state != "absent"
  tags: redis

- name: deploy redis_{{ port }} conf
  template: src=redis.conf dest=/etc/redis/{{ port }}/redis.conf
  when: state != "absent"
  tags: redis

- name: create {{ db_path }}/redis/{{ port }}
  file: path={{ db_path }}/redis/{{ port }} state=directory recurse=yes
  when: state != "absent"
  tags: redis

- name: start redis_{{ port }} service
  service: name=redis_{{ port }} enabled=yes state=started
  when: state != "absent"
  tags: redis

- name: stop redis_{{ port }} service
  service: name=redis enabled=no state=stopped
  when: state == "absent" 
  ignore_errors: true
  tags: redis

- name: rm redis init script
  file: dest=/etc/init.d/redis_{{ port }} state=absent
  when: state == "absent" 
  tags: redis

- name: rm {{ db_path }}/redis/{{ port }}
  file: dest={{ db_path }}/redis/{{ port }} state=absent
  when: state == "absent"
  tags: redis
