---
# The playbook for glusterfs client

- name: install gluster-epel.repo
  yum: name={{ item }} state={{ state }}
  with_items:
  - centos-release-gluster
  tags: glusterfs_client

- name: install fuse fuse-libs glusterfs glusterfs-fuse
  yum: name={{ item }} state={{ state }} 
  with_items:
  - fuse
  - fuse-libs
  - glusterfs
  - glusterfs-fuse
  tags: glusterfs_client
