#!/bin/sh
#
# mongodb     Startup script for the mongodb server
#
# chkconfig: - 86 15
# description: mongodb 
#
# processname: mongodb

# Source function library
. /etc/rc.d/init.d/functions

dir="{{ install_path }}/mongodb"
dbpath="{{ db_path }}/mongodb/{{ port }}"
[ ! -d $dbpath ] && mkdir -p $dbpath & chown -R {{ user }}:{{ user }} $dbpath
prog="mongodb_{{ port }}"
logfile="$dbpath/mongodb_{{ port }}.log"
pidfile="$dbpath/mongodb_{{ port }}.pid"
RETVAL=0

start() {
	ulimit -HSn 65536
	ulimit -HSu 65536
	echo never > /sys/kernel/mm/transparent_hugepage/enabled
	echo never > /sys/kernel/mm/transparent_hugepage/defrag
        echo -n $"Starting $prog: "
	{% if replSet is defined %}
        su {{ user }} -s '/bin/sh' -c "numactl --interleave=all $dir/bin/mongod --logpath $logfile --dbpath $dbpath --logappend  --fork --pidfilepath $pidfile --port {{ port }} --replSet {{ replSet }}"
        {% else %}
	su {{ user }} -s '/bin/sh' -c "numactl --interleave=all $dir/bin/mongod --logpath $logfile --dbpath $dbpath --logappend  --fork --pidfilepath $pidfile --port {{ port }}"
	{% endif %}
        RETVAL=$?
        echo
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        kill -2 `cat $pidfile`
        RETVAL=$?
        echo
	lock=$(cat $dbpath/mongod.lock)
	while [ ! -z $lock ]
	do
		sleep 1
		lock=$(cat $dbpath/mongod.lock)
	done	
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        status)
                status -p $pidfile
                RETVAL=$?
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac

exit $RETVAL
