#!/bin/sh
#
# mongodb     Startup script for the mongodb server
#
# chkconfig: - 86 15
# description: mongodb 
#
# processname: mongodb

# Source function library
. /etc/rc.d/init.d/functions

dir="{{ install_path }}/mongodb"
dbpath="{{ db_path }}/data/{{ port }}"
[ ! -d $dbpath ] && mkdir -p $dbpath
prog="mongodb_{{ port }}"
logfile="$dir/mongodb_{{ port }}.log"
pidfile="$dir/mongodb_{{ port }}.pid"
RETVAL=0

start() {
        ulimit -HSn 65536
        echo -n $"Starting $prog: "
        $dir/bin/mongod --logpath $logfile --dbpath $dbpath --logappend  --fork --pidfilepath $pidfile --port {{ port }}
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        kill -2 `cat $pidfile`
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        status)
                status -p $pidfile
                RETVAL=$?
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac

exit $RETVAL
