---
# The role for mysql-gmond
#
# Usage: { role: mysql-gmond, Host: localhost, Port: 3306, User: monitor, Password: monitor, Mysql: /usr/local/mysql/bin/mysql }
#

- name: mysql_{{ port }}.pyconf
  template: src=mysql.pyconf dest=/etc/ganglia/conf.d/mysql_{{port}}.pyconf
  notify: restart gmond
  when: state != "absent"
  tags: mysql-gmond

- name: mysql_{{ port }}.py
  template: src=mysql.py dest=/usr/lib64/ganglia/python_modules/mysql_{{port}}.py
  notify: restart gmond
  when: state != "absent"
  tags: mysql-gmond

- name: start gmond
  service: name=gmond state=started enabled=yes
  when: state != "absent"
  tags: mysql-gmond

- name: remove mysql_{{ port }}.py
  file: src=/usr/lib64/ganglia/python_modules/mysql_{{ port }}.py state=absent
  notify: restart gmond
  when: state == "absent"
  tags: mysql-gmond

- name: remove mysql_{{ port }}.pyconf
  file: src=/etc/ganglia/conf.d/mysql_{{ port }}.pyconf state=absent
  notify: restart gmond
  when: state == "absent"
  tags: mysql-gmond
