#!/bin/sh  
#  
# chkconfig: 345 99 01  
# description: Kafka  
#  
# File : Kafka  
#  
# Description: Starts and stops the Kafka server  
#  
  
source /etc/rc.d/init.d/functions  
export JAVA_HOME={{ install_path }}/jdk  
KAFKA_HOME={{install_path}}/kafka  
KAFKA_USER=root 
# See how we were called.  
start(){  
    echo -n "Starting Kafka:"  
    /sbin/runuser $KAFKA_USER -c "nohup $KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties > {{ log_path }}/kafka-logs/server.out 2> {{ log_path }}/kafka-logs/server.err &"  
    echo " done."  
}
  
stop(){  
    echo -n "Stopping Kafka: "  
    /sbin/runuser  $KAFKA_USER  -c "ps -ef | grep kafka.Kafka | grep -v grep | awk '{print \$2}' | xargs kill"  
    echo " done."  
}
  
case "$1" in  
  start)
  start
  ;;
  stop)
  stop
  ;;
  hardstop)  
    echo -n "Stopping (hard) Kafka: "  
    /sbin/runuser  $KAFKA_USER  -c "ps -ef | grep kafka.Kafka | grep -v grep | awk '{print \$2}' | xargs kill -9"  
    echo " done."  
    exit 0  
    ;;  
  
  status)  
    c_pid=`ps -ef | grep kafka.Kafka | grep -v grep | awk '{print $2}'`  
    if [ "$c_pid" = "" ] ; then  
      echo "Stopped"  
      exit 3  
    else  
      echo "Running $c_pid"  
      exit 0  
    fi  
    ;;  
  
  restart)  
    stop  
    start  
    ;;  
  
  *)  
    echo "Usage: cassandra {start|stop|hardstop|status|restart}"  
    exit 1  
    ;;  
  
esac  

