---
# default variables

#server.xml
maxThreads: 1000
minSpareThreads: 400
port: 8310
protocol: org.apache.coyote.http11.Http11NioProtocol
connectionTimeout: 20000
acceptCount: 2500
shutdown_port: 18310
context: [{"webapp":"osm-user.war","path":"/osm-user"},{"webapp":"osm-video","path":"/osm-video"}]

#catalina.sh
Xms: 2048m
Xmx: 2048m
Xmn: 128m
PermSize: 64m
MaxPermSize: 256m

#tomcat install path
install_path: /usr/local

#war dir
war_path: /usr/local/apps

#JAVA_HOME
java_home: /usr/local/jdk

#package path
package_path: /etc/ansible/packages 

#init script dir
init_path: /etc/init.d

#install or uninstall(choices:present,absent.default:absent)
state: present
