---
# The playbook for nrpe
#
# Usage: { role: nrpe, allowed_hosts: 10.3.1.0/24 }
#

- name: yum install nrpe
  yum: name={{ item }} state={{ state }} 
  with_items:
    - nrpe
    - nagios-plugins-all  
    - nsca-client
  tags: nrpe

- name: nrpe config
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg
  when: state != "absent"
  tags: nrpe 

- name: nsca config
  template: src=send_nsca.cfg dest=/etc/nagios/send_nsca.cfg
  when: state != "absent"
  tags: nrpe

- name: start nrpe
  service: name=nrpe state=started enabled=yes
  when: state != "absent"
  tags: nrpe

- name: check_sas 
  template: src=check_sas dest=/root/check_sas mode=0755
  when: state != "absent"
  tags: nrpe

- name: check_sas crontab
  cron: name="check_sas" minute=30 job="/root/check_sas {{ ansible_hostname }} > /dev/null 2>&1" backup=yes state={{ state }}
  tags: nrpe

- name: rm check_sas
  file: dest=/root/check_sas state=absent
  when: state == "absent"
  tags: nrpe
