#!/bin/sh
#
# nginx     Startup script for the nginx server
#
# chkconfig: - 85 15
# description: Lightning fast webserver with light system requirements
#
# processname: nginx
# config: /etc/lighttpd/lighttpd.conf
# config: /etc/sysconfig/lighttpd
# pidfile: /var/run/lighttpd.pid
#
# Note: pidfile is assumed to be created
# by lighttpd (config: server.pid-file).
# If not, uncomment 'pidof' line.

# Source function library
. /etc/rc.d/init.d/functions

CONF_PATH="{{ install_path }}/nginx/conf/nginx.conf"
prog="nginx"
BIN_PATH="{{ install_path }}/nginx/sbin/nginx"
RETVAL=0

start() {
        ulimit -HSn 65536
        echo -n $"Starting $prog: "
        daemon $BIN_PATH -c $CONF_PATH
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        killproc $BIN_PATH
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        condrestart)
                if [ -f /var/lock/subsys/$prog ]; then
                        stop
                        start
                fi
                ;;
	reload)
		kill -HUP `cat {{ install_path }}/nginx/logs/nginx.pid`
		;;
        status)
                status $BIN_PATH
                RETVAL=$?
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|condrestart|reload|status}"
                RETVAL=1
esac

exit $RETVAL
