---
# The playbook for ganglia-gmetad

- name: yum install ganglia-gmetad
  yum: name={{ item }} state={{ state }} 
  with_items:
    - ganglia-gmetad
    - ganglia-web
  tags: gmetad

- name: rsync gmetad.conf
  synchronize: src={{ package_path }}/ganglia/gmetad.conf dest=/etc/ganglia/gmetad.conf
  when: state != "absent"
  notify: restart gmetad
  tags: gmetad

- name: start gmetad
  service: name=gmetad state=started enabled=yes
  when: state != "absent"
  tags: gmetad
