---
# The playbook for system init

- name: yum install ganglia-gmetad
  yum: name=ganglia-gmetad state={{ state }} 
  with_items:
    - ganglia-gmetad
    - ganglia-web
  tags: gmetad

- name: start gmetad
  service: name=gmetad state=started enabled=yes
  when: state != "absent"
  tags: gmetad
