---
- name: mkdir /etc/kubernetes
  file: path=/etc/kubernetes state=directory
  tags: k8s_tls_node

- name: delete dir /etc/kubernetes/ssl
  file: path=/etc/kubernetes/ssl state=absent
  tags: k8s_tls_node

- name: mkdir /etc/kubernetes/ssl
  file: path=/etc/kubernetes/ssl state=directory
  tags: k8s_tls_node

- name: yum install docker flannel
  yum: name={{ item }} state=present
  with_items:
  - docker
  - flannel
  tags: k8s_tls_node

- name: change docker to use overlayfs storage driver and config flanneld
  template: src={{ item }} dest=/etc/sysconfig
  with_items:
  - docker-storage
  - flanneld
  tags: k8s_tls_node 

- name: modprobe overlay
  shell: modprobe overlay
  tags: k8s_tls_node

- name: rsync bootstrap.kubeconfig kube-proxy.kubeconfig
  synchronize: src=/root/ssl/{{ item }} dest=/etc/kubernetes
  with_items:
  - bootstrap.kubeconfig
  - kube-proxy.kubeconfig
  tags: k8s_tls_node

- name: delete kubelet.kubeconfig
  file: path=/etc/kubernetes/kubelet.kubeconfig state=absent
  tags: k8s_tls_node

- name: rsync kubectl kubelet kube-proxy
  synchronize: src={{ package_path }}/kubernetes/{{ kubernetes_version }}/{{ item }} dest=/usr/bin
  with_items:
  - kubectl
  - kubelet
  - kube-proxy
  tags: k8s_tls_node

- name: deploy kubelet kube-proxy config
  template: src={{ item }} dest=/etc/kubernetes
  with_items:
  - config
  - kubelet
  - proxy
  tags: k8s_tls_node  

- name: deploy kubelet kube-proxy service
  template: src={{ item }} dest=/usr/lib/systemd/system
  with_items:
  - kubelet.service
  - kube-proxy.service
  tags: k8s_tls_node

- name: systemctl enable kubelet kube-proxy
  shell: systemctl enable {{ item }}
  with_items:
  - kubelet
  - kube-proxy
  tags: k8s_tls_node

- name: disable selinux
  command: setenforce 0
  ignore_errors: true
  tags: k8s_tls_node

- name: disable firewalld
  command: systemctl disable firewalld
  tags: k8s_tls_node

- name: stop firewalld
  command: systemctl stop firewalld
  tags: k8s_tls_node

- name: stop swap
  shell: swapoff -a
  tags: k8s_tls_node

- name: set docker0 promisc on
  shell: ip link set docker0 promisc on
  tags: k8s_tls_node

- name: swapoff add to /etc/rc.local
  lineinfile: path=/etc/rc.local line='swapoff -a' state=present
  tags: k8s_tls_node

- name: set docker0 promisc on to /etc/rc.local
  lineinfile: path=/etc/rc.local line='ip link set docker0 promisc on' state=present
  tags: k8s_tls_node

- name: mkdir kubelet working directory /var/lib/kubelet
  file: path=/var/lib/kubelet state=directory
  tags: k8s_tls_node

- name: systemctl start flanneld docker kubelet kube-proxy
  shell: systemctl restart {{ item }}
  with_items:
  - flanneld
  - docker
  - kubelet
  - kube-proxy
  tags: k8s_tls_node
