---
kubernetes_hosts: "192.168.1.1,192.168.1.2" #部署master的节点IP，会包含在生成的kube-apiserver证书中
kubernetes_cname: "test.com,foo.com"  #kube-apiserver证书中使用
kube_apiserver: "192.168.1.1" #只能指定一个IP
kubernetes_version: "1.11.2"   #二进制文件存放在file目录下对应的版本文件夹中
pod_ip_range: "172.30.0.0/16"
etcd_servers: "http://192.168.1.1:2379"  #http访问
service_ip_range: "10.254.0.0/16"
cluster_dns: "10.254.0.2"
cluster_domain: "cluster.local"
coredns_image: "coredns/coredns:1.1.3"
storage_backend: "etcd3"   #1.13版本开始只能使用etcd3
k8s_tls_master_state: present
kubernetes_cluster: new  #新部署的节点使用new，如果是重复部署或者是扩容，则使用exist，new状态下会重新生成证书
kubernetes_cluster_name: test  #全局唯一，避免证书错乱
calico_node_image: "calico/node:v3.1.3"
calico_cni_image: "calico/cni:v3.1.3"
calico_controllers_image: "calico/kube-controllers:v3.1.3"
docker_root_dir: "/var/lib/docker"   #docker的根目录
metrics_server_image: "google_containers/metrics-server-amd64:v0.2.1"
