---
- name: yum install etcd
  yum: name=etcd state={{ state }}
  tags: etcd

- name: mkdir {{ etcd_data_dir }}/etcd
  file: path={{ etcd_data_dir }}/etcd owner=etcd group=etcd state=directory
  when: state != "absent"

- name: deploy etcd.conf
  template: src=etcd.conf dest=/etc/etcd/ mode=0644
  when: state != "absent"
  tags: etcd

- name: deploy etcd.service
  template: src=etcd.service dest=/usr/lib/systemd/system/ mode=0644
  when: state != "absent"
  tags: etcd

- name: start etcd
  service: name=etcd enabled=yes state=started
  when: state != "absent"
  tags: etcd
