#!/usr/bin/env bash
# chkconfig: 2345 40 50
# description: Kafka
stop()
{
    kill `cat {{ install_path }}/ssdb/var/ssdb.pid`
    echo "ssdb stopped."
    sleep 1
}

start()
{
    {{ install_path }}/ssdb/bin/ssdb-server -d {{ install_path }}/ssdb/conf/ssdb.conf
    echo "ssdb started."
}

status()
{
    c_pid=`cat {{ install_path }}/ssdb/var/ssdb.pid`
    if [ "$c_pid" = "" ] ; then
      echo "Stopped"
      exit 3
    else
      echo "Running $c_pid"
      exit 0
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

