#!/bin/sh
#
# redis     Startup script for the redis server
#
# chkconfig: - 87 15
# description: redis 
#
# processname: redis

# Source function library
. /etc/rc.d/init.d/functions

prog="redis"
REDISPORT=6379
EXEC={{ install_path }}/redis/bin/redis-server
CLIEXEC={{ install_path }}/redis/bin/redis-cli
DATADIR={{ db_path }}/redis
[ ! -d $DATADIR ] && mkdir -p $DATADIR

PIDFILE=/var/run/redis.pid
CONF="{{ install_path }}/redis/redis.conf"

start() {
	echo -n $"Starting $prog: "
	sysctl -w vm.overcommit_memory=1
	$EXEC $CONF
	RETVAL=$?
	echo 
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	PID=$(cat $PIDFILE)
	$CLIEXEC -p $REDISPORT shutdown
	while [ -x /proc/${PID} ]
        do
        	echo "Waiting for Redis to shutdown ..."
                sleep 1
       	done
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

case "$1" in
    start)
	start
        ;;
    stop)
	stop
        ;;
    restart)
	stop
	start
	;;
    status)
        status -p $PIDFILE
        RETVAL=$?
       	;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
	RETVAL=1
        ;;
esac

exit $RETVAL
