---
# The playbook for tomcat deploy

- name: Create tomcat dir  
  file: path={{ tomcat_path }} state=directory
  when: state != "absent"
  tags: tomcat

- name: yum install cronolog
  yum: name=cronolog state=present
  when: state != "absent"
  tags: tomcat

- name: Create tomcat_{{ port }} dir
  file: path={{ tomcat_path }}/tomcat_{{ port }} state=directory
  when: state != "absent"
  tags: tomcat

- name: check tomcat
  command: "ls {{ tomcat_path }}/tomcat_{{ port }}/bin/catalina.sh"
  register: tomcat_result
  ignore_errors: true
  when: state != "absent"
  tags: tomcat

- name: deploy tomcat_{{ port }}
  #copy: src=tomcat_8310 dest=/tmp/tomcat 
  synchronize: src={{ package_path }}/tomcat/tomcat_8310/ dest={{ tomcat_path }}/tomcat_{{ port }}/ 
  when: tomcat_result is defined and tomcat_result.rc !=0 or state == "upgrade"
  tags: tomcat

- name: deploy server.xml
  template: src=server.xml dest={{ tomcat_path }}/tomcat_{{ port }}/conf/server.xml
  when: state != "absent"
  tags: tomcat

- name: deploy Catalina.sh
  template: src=catalina.sh dest={{ tomcat_path }}/tomcat_{{ port }}/bin/catalina.sh mode=0755
  when: state != "absent"
  tags: tomcat

- name: deploy tomcat.sh
  synchronize: src={{ package_path }}/tomcat/tomcat.sh dest={{ init_path }}/tomcat.sh
  when: state != "absent"
  tags: tomcat

- name: rm tomcat_{{ port }}
  file: dest={{ tomcat_path }}/tomcat_{{ port }} state=absent
  when: state == "absent"
  tags: tomcat
