---
# The playbook for jdk deploy

- name: Deploy jdk
  synchronize: src={{ package_path }}/jdk/{{ jdk_file }} dest={{ install_path }}
  when: state != "absent"
  tags: jdk

- name: ln -s {{ install_path }}/{{ jdk_file }} {{ install_path }}/jdk
  file: src={{ install_path }}/{{ jdk_file }} dest={{ install_path }}/jdk state=link
  when: state != "absent"
  tags: jdk

- name: rm jdk symbolic link
  file: dest={{ install_path }}/jdk state=absent
  when:  state  == "absent"
  tags: jdk

- name: rm jdk
  file: dest={{ install_path }}/{{ jdk_file }} state=absent
  when:  state == "absent"
  tags: jdk
