---
# The playbook for openresty

- name: check nginx
  shell: "{{ install_path }}/nginx/sbin/nginx -v"
  register: nginx_result
  ignore_errors: true
  when: state != "absent"

- name: yum install pcre-devel
  yum: name={{ item }}
  with_items:
   - pcre-devel
   - openssl-devel
  when: state != "absent"

- name: rsync nginx
  synchronize: src={{ package_path }}/openresty/openresty-{{ version }} dest=/tmp
  when: nginx_result is defined and nginx_result.stderr.find('nginx version') == -1 or state == "upgrade" 

- name: configure nginx
  command: "chdir=/tmp/openresty-{{ version }} ./configure --prefix={{ install_path }} --with-stream"
  when: nginx_result is defined and nginx_result.stderr.find('nginx version') == -1 or state == "upgrade"

- name: make nginx
  command: "chdir=/tmp/openresty-{{ version }} make -j8"
  when: nginx_result is defined and nginx_result.stderr.find('nginx version') == -1 or state == "upgrade"

- name: make install nginx
  command: "chdir=/tmp//tmp/openresty-{{ version }} make install"
  when: nginx_result is defined and nginx_result.stderr.find('nginx version') == -1 or state == "upgrade"

- name: deploy {{ conf }}
  synchronize: src={{ package_path }}/openresty/{{ conf }} dest={{ install_path }}/nginx/conf/nginx.conf
  when: state != "absent" 

- name: deploy nginx init script
  template: src=nginx dest=/etc/init.d/nginx mode=0755
  when: state != "absent"

- name: start nginx service
  service: name=nginx enabled=yes state=started
  when: state != "absent"

- name: stop nginx service
  service: name=nginx enabled=no state=stopped
  when: state == "absent" 
  ignore_errors: true

- name: uninstall nginx
  file: dest={{ install_path }}/nginx state=absent
  when: state == "absent"

- name: rm nginx init script
  file: dest=/etc/init.d/nginx state=absent
  when: state == "absent" 
