---
# The playbook for glusterfs-server

- name: install gluster-epel.repo
  yum: name={{ item }} state={{ state }}
  with_items:
  - centos-release-gluster
  tags: glusterfs_server

- name: install glusterfs-server
  yum: name={{ item }} state={{ state }} 
  with_items:
  - glusterfs-server
  tags: glusterfs_server
